version: 0.2
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=devsecop0 -Dsonar.organization=devsecop0 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=b598fbbd6aff49f7d5162f900f1da7c9eaaf7154 
